
services:
  redis_dashboards:
    image: redis:7-alpine
    restart: always
    # ports:
    #   - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_dashboards_data:/data
    networks:
      - nginx-proxy-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  web_dashboards:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_REDIS_URL: ${NEXT_PUBLIC_REDIS_URL}
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      NEXT_PUBLIC_NODE_ENV: ${NEXT_PUBLIC_NODE_ENV}
      NEXT_PUBLIC_LOG_LEVEL: ${NEXT_PUBLIC_LOG_LEVEL}
      NEXT_PUBLIC_BOT_API: ${NEXT_PUBLIC_BOT_API}
    depends_on:
      redis_dashboards:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    user: "root"
    networks:
      - nginx-proxy-network

volumes:
  redis_dashboards_data:

networks:
  nginx-proxy-network:
    external: true
    name: nginx_network_nginx-proxy-network